name: Matrix

on:
  workflow_dispatch:

  jobs:
    echo-matrix:
    name: ${{matrix.os}} - ${{matrix.node-version}}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        node-version: [v18.0.0 , v21.0.0]
        os:
          -  ubuntu-latest
          -  windows-latest
      steps:
        -  uses: action/setup-nodejs@v4
           with:
           node-version: ${{matrix.node-version}}
      
    
