name: Matrix

on:
  workflow_dispatch:

jobs:
  echo-matrix:
    name: ${{matrix.os}} - ${{matrix.node-version}}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        node-version: [v22.6.0 , v21.7.3]
        os:
          - ubuntu-latest
          - windows-latest
    steps:
        - uses: actions/setup-node@v4.0.1
          with:
            node-version: ${{matrix.node-version}}
      
    
