name: SecondWorkflow
# Tiiger part
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: ' * * * * * '

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      -  name: first step Dev
         run: echo "First worlflow"
  
