name: How to define Varibales

on:
  workflow_dispatch:

jobs:
  variables:
    runs-on: ubuntu-latest
    steps:
      - name: Variables
        run: echo " Value for Varibales stored ${{vars.MY_VAR}}"
        run: echo "Secret API Key value to be used ${{secrets.API_KEY}}"
  
  
